
name: CI
on: [push]
jobs:
  build:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test